name: uyava_ui
description: Shared Flutter UI for Uyava graph rendering (painter, geometry, policies, configs).
publish_to: 'none'
version: 0.2.1-beta.1
homepage: https://uyava.io
repository: https://github.com/alex-marochko/uyava
issue_tracker: https://github.com/alex-marochko/uyava/issues
documentation: https://uyava.io/docs

environment:
  sdk: ^3.10.0-75.1.beta

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  uyava_core:
    path: ../uyava_core
  uyava_protocol:
    path: ../uyava_protocol

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
