import 'package:test/test.dart';
import 'package:uyava_protocol/uyava_protocol.dart';

void main() {
  test('default diagnostic levels follow repository policy', () {
    expect(
      UyavaGraphIntegrityCode.nodesInvalidColor.defaultLevel,
      UyavaDiagnosticLevel.warning,
    );
    expect(
      UyavaGraphIntegrityCode.nodesInvalidShape.defaultLevel,
      UyavaDiagnosticLevel.warning,
    );
    expect(
      UyavaGraphIntegrityCode.nodesConflictingColor.defaultLevel,
      UyavaDiagnosticLevel.warning,
    );
    expect(
      UyavaGraphIntegrityCode.nodesConflictingTags.defaultLevel,
      UyavaDiagnosticLevel.warning,
    );
    expect(
      UyavaGraphIntegrityCode.nodesDuplicateId.defaultLevel,
      UyavaDiagnosticLevel.warning,
    );
    expect(
      UyavaGraphIntegrityCode.nodesMissingId.defaultLevel,
      UyavaDiagnosticLevel.error,
    );
    expect(
      UyavaGraphIntegrityCode.edgesDuplicateId.defaultLevel,
      UyavaDiagnosticLevel.warning,
    );
    expect(
      UyavaGraphIntegrityCode.edgesMissingId.defaultLevel,
      UyavaDiagnosticLevel.error,
    );
    expect(
      UyavaGraphIntegrityCode.edgesMissingSource.defaultLevel,
      UyavaDiagnosticLevel.error,
    );
    expect(
      UyavaGraphIntegrityCode.edgesMissingTarget.defaultLevel,
      UyavaDiagnosticLevel.error,
    );
    expect(
      UyavaGraphIntegrityCode.edgesDanglingSource.defaultLevel,
      UyavaDiagnosticLevel.error,
    );
    expect(
      UyavaGraphIntegrityCode.edgesDanglingTarget.defaultLevel,
      UyavaDiagnosticLevel.error,
    );
    expect(
      UyavaGraphIntegrityCode.edgesSelfLoop.defaultLevel,
      UyavaDiagnosticLevel.error,
    );
  });
}
